import logging

# database
MIGRATIONS_DIRECTORY = "migrations"
DATABASE_DIRECTORY = "db"
DATABASE_NAME = "training_data.db"

# training data generation
INTEGRATION_VARIABLE_NAME = "x"
INTEGRATION_TIMEOUT = 5
FUNCTION_COMPLEXITY = 10
DATA_GENERATION_BATCH_SIZE = 50
DATA_GENERATION_BATCH_TIMEOUT_SECONDS = 60

# models
MODEL_DIRECTORY = "models"
MODEL_NAME = "intclass"

# logging
LOG_LEVEL = logging.DEBUG
